# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

 

# Example 1:

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:

# Input: s = "", t = "y"
# Output: "y"


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        
        d = {}
        for i in range(len(t)):
            d[t[i]] = d.get(t[i],0) + 1
        for i in range(len(s)):
            d[s[i]] = d.get(s[i],0) - 1
        for j in d:
            if d[j] == 1:
                return j
        